name = "chatgpt-ads-library"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "chatgpt-ads-library"
database_id = "af82e074-3db7-45fc-b2ab-d3e446f47f33"

[[r2_buckets]]
binding = "ADS_IMAGES"
bucket_name = "chatgpt-ads-library-images"
