// Generated by Wrangler by running `wrangler types -c worker/wrangler.toml --env-interface CloudflareBindings worker/src/env.d.ts`

interface CloudflareBindings {
	ADS_IMAGES: R2Bucket;
	DB: D1Database;
}
