// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/advertisers": {
    params: {};
  };
  "/advertisers/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ads/:id": {
    params: {
      "id": string;
    };
  };
  "/about": {
    params: {};
  };
  "/api/ads": {
    params: {};
  };
  "/api/advertisers": {
    params: {};
  };
  "/api/stats": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/advertisers" | "/advertisers/:slug" | "/ads/:id" | "/about" | "/api/ads" | "/api/advertisers" | "/api/stats" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/advertisers._index.tsx": {
    id: "routes/advertisers._index";
    page: "/advertisers";
  };
  "routes/advertisers.$slug.tsx": {
    id: "routes/advertisers.$slug";
    page: "/advertisers/:slug";
  };
  "routes/ads.$id.tsx": {
    id: "routes/ads.$id";
    page: "/ads/:id";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/api.ads.ts": {
    id: "routes/api.ads";
    page: "/api/ads";
  };
  "routes/api.advertisers.ts": {
    id: "routes/api.advertisers";
    page: "/api/advertisers";
  };
  "routes/api.stats.ts": {
    id: "routes/api.stats";
    page: "/api/stats";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/advertisers._index": typeof import("./app/routes/advertisers._index.tsx");
  "routes/advertisers.$slug": typeof import("./app/routes/advertisers.$slug.tsx");
  "routes/ads.$id": typeof import("./app/routes/ads.$id.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/api.ads": typeof import("./app/routes/api.ads.ts");
  "routes/api.advertisers": typeof import("./app/routes/api.advertisers.ts");
  "routes/api.stats": typeof import("./app/routes/api.stats.ts");
  "routes/$": typeof import("./app/routes/$.tsx");
};