import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const OUT = join(root, "frontend", "seed.sql");
const SCHEMA = readFileSync(join(root, "frontend", "schema.sql"), "utf8");
const ADS = JSON.parse(readFileSync(join(root, "data", "ads.json"), "utf8"));
const ADVERTISERS = JSON.parse(readFileSync(join(root, "data", "advertisers.json"), "utf8"));

let CATEGORIES = [];
let AD_CATEGORIES = {};
try {
  CATEGORIES = JSON.parse(readFileSync(join(root, "data", "categories.json"), "utf8"));
  AD_CATEGORIES = JSON.parse(readFileSync(join(root, "data", "ad_categories.json"), "utf8"));
} catch (e) {
  console.warn("Warning: categories.json or ad_categories.json not found — skipping category seeding.");
}

function sqlString(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlValue(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return sqlString(value);
}

const lines = [
  "-- Generated by scripts/generate-seed.mjs. Do not edit by hand.",
  "",
  SCHEMA.trim(),
  "",
];

for (const a of ADS) {
  const values = [
    a.id,
    a.advertiserSlug,
    a.advertiserName,
    a.advertiserLogo,
    a.advertiserPageUrl,
    a.websiteUrl,
    a.websiteDomain,
    a.copy,
    a.description,
    a.mediaUrl,
    a.publishedDate,
    a.impressions,
  ]
    .map(sqlValue)
    .join(", ");

  lines.push(
    `INSERT OR REPLACE INTO ads (id, advertiser_slug, advertiser_name, advertiser_logo, advertiser_page_url, website_url, website_domain, copy, description, media_url, published_date, impressions) VALUES (${values});`
  );
}

for (const a of ADVERTISERS) {
  const values = [
    a.slug,
    a.name,
    a.logo,
    a.websiteUrl,
    a.websiteDomain,
    a.adCount,
    a.totalImpressions,
    a.firstSeen,
    a.lastSeen,
  ]
    .map(sqlValue)
    .join(", ");

  lines.push(
    `INSERT OR REPLACE INTO advertisers (slug, name, logo, website_url, website_domain, ad_count, total_impressions, first_seen, last_seen) VALUES (${values});`
  );
}

// Seed categories
for (const cat of CATEGORIES) {
  const catData = AD_CATEGORIES[cat.slug] || { adCount: 0, advertiserCount: 0 };
  const values = [
    cat.slug,
    cat.name,
    cat.title,
    cat.description,
    catData.adCount || 0,
    catData.advertiserCount || 0,
  ]
    .map(sqlValue)
    .join(", ");

  lines.push(
    `INSERT OR REPLACE INTO categories (slug, name, title, description, ad_count, advertiser_count) VALUES (${values});`
  );
}

// Seed ad_categories mappings
let mappingCount = 0;
for (const [catSlug, catData] of Object.entries(AD_CATEGORIES)) {
  for (const adId of (catData.adIds || [])) {
    lines.push(
      `INSERT OR REPLACE INTO ad_categories (ad_id, category_slug) VALUES (${sqlString(adId)}, ${sqlString(catSlug)});`
    );
    mappingCount++;
  }
}

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT}`);
console.log(`  ads: ${ADS.length}`);
console.log(`  advertisers: ${ADVERTISERS.length}`);
console.log(`  categories: ${CATEGORIES.length}`);
console.log(`  ad-category mappings: ${mappingCount}`);

