import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const OUT = join(root, "api", "seed.sql");
const SCHEMA = readFileSync(join(root, "api", "schema.sql"), "utf8");
const ADS = JSON.parse(readFileSync(join(root, "data", "ads.json"), "utf8"));
const ADVERTISERS = JSON.parse(readFileSync(join(root, "data", "advertisers.json"), "utf8"));

function sqlString(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlValue(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return sqlString(value);
}

const lines = [
  "-- Generated by scripts/generate-seed.mjs. Do not edit by hand.",
  "",
  SCHEMA.trim(),
  "",
];

for (const a of ADS) {
  const values = [
    a.id,
    a.advertiserSlug,
    a.advertiserName,
    a.advertiserLogo,
    a.advertiserPageUrl,
    a.websiteUrl,
    a.websiteDomain,
    a.copy,
    a.description,
    a.mediaUrl,
    a.publishedDate,
    a.impressions,
  ]
    .map(sqlValue)
    .join(", ");

  lines.push(
    `INSERT OR REPLACE INTO ads (id, advertiser_slug, advertiser_name, advertiser_logo, advertiser_page_url, website_url, website_domain, copy, description, media_url, published_date, impressions) VALUES (${values});`
  );
}

for (const a of ADVERTISERS) {
  const values = [
    a.slug,
    a.name,
    a.logo,
    a.websiteUrl,
    a.websiteDomain,
    a.adCount,
    a.totalImpressions,
    a.firstSeen,
    a.lastSeen,
  ]
    .map(sqlValue)
    .join(", ");

  lines.push(
    `INSERT OR REPLACE INTO advertisers (slug, name, logo, website_url, website_domain, ad_count, total_impressions, first_seen, last_seen) VALUES (${values});`
  );
}

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT}`);
console.log(`  ads: ${ADS.length}`);
console.log(`  advertisers: ${ADVERTISERS.length}`);
